### ISSUE TITLE
Image & rich text editor widgets don't appear to be incomplete 

### ISSUE THREAD

**Issue by moseley** [kaneohe/kaneohe#2]
Adding an image widget or rich text editor widget appears to just have a title. If added it displays Hello World.

Not sure if there is an ACF file that needs to be imported.

Alternatively, we can look into the [Advanced Custom Fields: Widget Area Field](https://wordpress.org/plugins/advanced-custom-fields-widget-area-field/installation/) plugin.

**Comment by briangunzenhauser** [comment]
Do the widget fields appear under Appearance > Widgets? If so, they'll be empty until an ACF field group is created for them. This should allow us to bypass the plugin.

**Comment by moseley** [comment]
Deleted additional widgets went to theme options acf
